### ISSUE TITLE
Contrast ratio is too low for the element description text.

### ISSUE THREAD

**Issue by Roger-Heathcote** [suhdonghwi/3d-periodic-table#1]
The grey text on a grey background looks elegant but is hard to read, especially at the smaller font size. The ANSI minimum recommended contrast ratio is 3:1 and the W3 WCAG2.1 guidelines suggest a contrast ratio of 4.5:1 for AA accessibility (accounting for people in old age, those with moderately low visual acuity and those with color blindness).

Love the site btw, looking forward to showing it to my kids later!

**Comment by TrentSterling** [comment]
Agreed! Made a comment on the reddit thread about the contrast. Hopefully we get less _grey on grey_!

**Comment by suhdonghwi** [comment]
Thank you for the suggestion! I will improve it now.

**Comment by suhdonghwi** [comment]
I improved it, how does it look now? :)

https://periodic.donghwi.dev
