### ISSUE TITLE
Z-Sorting flickers Element symbols when camera angle is 90 degrees top-view

### ISSUE THREAD

**Issue by TrentSterling** [suhdonghwi/3d-periodic-table#2]
When the camera orbit is directly above, there is Z-fighting of the text against the graph .... cubes... (sorry idk the right terms lol)

![chrome_0QATEIAtRw](https://user-images.githubusercontent.com/2933217/101475953-a1b32980-3912-11eb-8841-ae98e47971bb.png)

This could be fixed by simply offsetting the text a little bit higher, or by setting up some kind of render layers

**Comment by suhdonghwi** [comment]
It already has depth offset, but it seems that I should increase it. Thank you!
