### ISSUE TITLE
Reduce the size of the repo

### ISSUE THREAD

**Issue by ahampriyanshu** [suhdonghwi/3d-periodic-table#3]
You can use ``githubusercontent`` to store _demo.gif_  and reduce the size of this repo by 98%.

**Comment by ahampriyanshu** [comment]
![demo](https://user-images.githubusercontent.com/54521023/101487465-36a23b00-3984-11eb-8115-65669c9e5b13.gif)
 
Just Use ``![demo](https://user-images.githubusercontent.com/54521023/101487465-36a23b00-3984-11eb-8115-65669c9e5b13.gif)`` and delete the orginal file.
Now your repo weighs 260 Kb instead of 10 mB

**Comment by suhdonghwi** [comment]
Thank you for suggestion! I wonder if that link is permanent or temporary?

**Comment by ahampriyanshu** [comment]
I'm pretty sure it is permanent.(as long as the repository or the issue isn't deleted) 
So if you want you can create a new issue and attach the gif file over there.
How I use [it](https://github.com/ahampriyanshu/aanav/issues?q=is%3Aissue+is%3Aclosed).

**Comment by suhdonghwi** [comment]
Thank you much! I changed link and removed original image.

**Comment by ahampriyanshu** [comment]
No problem
